package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marwah
 */
public class ViewPreProcessing extends javax.swing.JFrame {

    /**
     * Creates new form guita
     */
    public ViewPreProcessing() {
        initComponents();
    }

    public JTextArea getTxt_berita_asli() {
        return txt_berita_asli;
    }

    public void setTxt_berita_asli(JTextArea txt_berita_asli) {
        this.txt_berita_asli = txt_berita_asli;
    }

    public JTextArea getTxt_punctuation() {
        return txt_punctuation;
    }

    public void setTxt_punctuation(JTextArea txt_punctuation) {
        this.txt_punctuation = txt_punctuation;
    }

    public JLabel getTxt_judul_berita() {
        return txt_judul_berita;
    }

    public JButton getBtn_cek_berita_lagi() {
        return btn_cek_berita_lagi;
    }

    public JButton getBtn_keluar() {
        return btn_keluar;
    }

    public JScrollPane getScroll_table_preprocessing() {
        return scroll_table_preprocessing;
    }

    public void setScroll_table_preprocessing(JScrollPane scroll_table_preprocessing) {
        this.scroll_table_preprocessing = scroll_table_preprocessing;
    }

    public JTable getTable_preprocessing() {
        return table_preprocessing;
    }

    public void setTable_preprocessing(JTable table_preprocessing) {
        this.table_preprocessing = table_preprocessing;
    }
    
    
    
    public void addListener (ActionListener a){
        btn_keluar.addActionListener(a);
        btn_cek_berita_lagi.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_judul_berita = new javax.swing.JLabel();
        btn_keluar = new javax.swing.JButton();
        btn_cek_berita_lagi = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_berita_asli = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_punctuation = new javax.swing.JTextArea();
        scroll_table_preprocessing = new javax.swing.JScrollPane();
        table_preprocessing = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Text Pre Processing");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Berita Asli");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Remove Punctuation");

        txt_judul_berita.setBackground(new java.awt.Color(255, 255, 255));
        txt_judul_berita.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_judul_berita.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_judul_berita.setText("Judul Berita");

        btn_keluar.setText("Keluar");

        btn_cek_berita_lagi.setText("Cek Berita Lagi");

        txt_berita_asli.setColumns(20);
        txt_berita_asli.setRows(5);
        jScrollPane7.setViewportView(txt_berita_asli);

        txt_punctuation.setColumns(20);
        txt_punctuation.setRows(5);
        jScrollPane1.setViewportView(txt_punctuation);

        table_preprocessing.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll_table_preprocessing.setViewportView(table_preprocessing);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txt_judul_berita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btn_cek_berita_lagi)
                .addGap(46, 46, 46)
                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
            .addComponent(scroll_table_preprocessing)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_judul_berita)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scroll_table_preprocessing, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cek_berita_lagi)
                    .addComponent(btn_keluar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cek_berita_lagi;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane scroll_table_preprocessing;
    private javax.swing.JTable table_preprocessing;
    private javax.swing.JTextArea txt_berita_asli;
    private javax.swing.JLabel txt_judul_berita;
    private javax.swing.JTextArea txt_punctuation;
    // End of variables declaration//GEN-END:variables
}
